### ISSUE TITLE
Searches for "whiskey" should find bourbon, rye, and scotch

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#1]
Would like to be able to search ingredients within a cocktail.  Additionally, a search for 'whiskey' should also bring up drinks with bourbon and rye; and a search of 'whisky' should bring up scotch.

**Comment by funrollloops** [comment]
searching for ingredients within a cocktail was done in 59e886609894e2e5d407d0d41b70550e004f7362

searching for synonyms is a little trickier

**Comment by wgmfisch** [comment]
Makes sense.

**Comment by audiodude** [comment]
This issue was moved to audiodude/nebree8.com#1
