### ISSUE TITLE
Sliders select when previously highlighted (in phone)

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#13]
When selecting a drink from the main list on a touch screen interface, if your selection is at the same height on the page as a slider, that slider comes up with the larger slider knob (as if it had been selected).

**Comment by wgmfisch** [comment]
Doesn't seem to happen on a non-mobile platform.

**Comment by funrollloops** [comment]
Can probably be fixed by adding a transition, to give you time to lift your finger.

**Comment by wgmfisch** [comment]
Seems like a good plan.

**Comment by funrollloops** [comment]
Fixed with an animation in d616656a2f7ad18fe85bbcd52dbfe398ecf41271
