### ISSUE TITLE
Close button on search bar

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#15]
The 'x' on the search bar doesn't clear the search line.  Perhaps something where you have a back arrow to remove searching and an 'x' to clear the search field?  That seems to be common practice these days.

**Comment by wgmfisch** [comment]
Similarly, when that 'x' is pressed currently, the existing search term still limits the available options for selection.

**Comment by wgmfisch** [comment]
And if you select a drink, then cancel back, it takes you to the main list instead of to your search.

**Comment by funrollloops** [comment]
Really good feedback, thanks! I'll work on fixing this.

**Comment by funrollloops** [comment]
Fixed in b9462bd259012f8e578bb448729f2e57fe3399cb, b2742a9039d8ed41a6b78849fd0c4265e26e93bf, 39559ec4e64e55bd806b4c1a8a05d090af2c6d14, d426a4b196b60ad988190894fd245b7103acf954
