### ISSUE TITLE
Change randomizer

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#2]
As per whiteboard drawing; so that only one random option exists and it's at the top of the (otherwise) alphabetized list on the main page.  Not sure if we decided for it to tell what drink it's thinking of making first or not.

**Comment by funrollloops** [comment]
Done in 2a7879be3e797d5a0eef2d9941fe885045aec53d

**Comment by wgmfisch** [comment]
Bitters not randomizing.

Multiple of the same type of ingredient not happening.

**Comment by wgmfisch** [comment]
The bitters is showing up, but I have yet to see two hard liquors show up
in the same drink.

**Comment by funrollloops** [comment]
I haven't implemented multiple liquors (roughly speaking). Are you sure we
want this? I think it results in much less drinkable drinks.

**Comment by wgmfisch** [comment]
I don't want it in every drink, but I think it's a generally good idea.  It
comes up in lots of cocktails.  It does probably increase the
weird-quotient of our drinks, but that's half of the charm.  If we can tune
it so that it only pulls in a second similar ingredient 20% of the time, I
think that's a good compromise.
