### ISSUE TITLE
Horizontal scroll bar visible when sliders are maxed out

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#20]
![slider bar](https://cloud.githubusercontent.com/assets/13283873/10416149/944883da-6fbe-11e5-9a50-51a3a2469a9b.png)

**Comment by funrollloops** [comment]
Can you explain what you mean by "peculiar"? The screenshot looks normal to
me.

**Comment by wgmfisch** [comment]
It's adding in a second scroll bar at the bottom because the slider, when
expanded, takes up slightly more than the frame.

We may want to compress the sliders down to only 5 notches and scoot things
over to accommodate a picture anyway. Thoughts?

**Comment by funrollloops** [comment]
Yeah, some padding should fix it.

**Comment by wgmfisch** [comment]
Great, sounds good.

**Comment by funrollloops** [comment]
Fixed in 73d018c4c79394664350a147e0f477f8d14de7c4
