### ISSUE TITLE
Make it easier to figure out the difference between gin martinis

### ISSUE THREAD

**Issue by funrollloops** [nebree8/nebree8.com#21]
The dry, perfect, and original martinis have the same ingredients but in different ratios. It's hard to decide between them just based on the information in the app  -- especially now that ratios aren't visible even on the detail screen now.

**Comment by funrollloops** [comment]
We've decided to fix this by (1) having only one martini show in the list by default (2) adding a description with links to the other kinds of martinis.

**Comment by audiodude** [comment]
This issue was moved to audiodude/nebree8.com#4
