### ISSUE TITLE
Add random drink random name generator

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#26]
See Will for comments.  Definitely fluffy icing on the cake.  But how awesome would it be if you hit 'random drink' and it made you a drink called a 'Whistling Ghost Fart' or a 'Dragon's Guilt' or some shit. And then it would toss your name on it.

**Comment by funrollloops** [comment]
You could probably do this, if you wanted. It would be a good programming
exercise.

You could do it Diablo style -- map each liquor and mixer to a suffix or
prefix, and build up a name like "Sparkling Florida Bog" for a drink with
champagne, orange juice, and Laphroaig. Or you could put together totally
random adjectives, nouns, and adverbs.

**Comment by wgmfisch** [comment]
I think I'd rather have it completely random adjectives, nouns, and
adverbs.  What language would be best to do this?

**Comment by funrollloops** [comment]
Since we do drink generation on the client, probably client side. If you
want to use a large dictionary though you should do server side (in Go).

**Comment by wgmfisch** [comment]
I'll probably use only a handful of carefully chosen words, no more than
250 certainly.  Does that count as small dictionary?

Never used Go before. Any trick to it?

**Comment by funrollloops** [comment]
golang.org/tour to learn go online

250 words is tiny, you could put that on the client in Javascript.

**Comment by wgmfisch** [comment]
I'll probably work on it this weekend while Lani is out of town.  Can I
harass you for help if I need it?

**Comment by audiodude** [comment]
I believe this is done.
