### ISSUE TITLE
Sliders on Scotch (neat)

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#3]
You can turn up the concentration of scotch in a drink which is all scotch?  And has the same volume regardless?

**Comment by funrollloops** [comment]
What should the UI look like here?

**Comment by wgmfisch** [comment]
No slider at all? I mean, it's a neat scotch?

**Comment by funrollloops** [comment]
I mean, sure, but it'll be a little bare -- just a header and an order button? We can see what it looks like.

**Comment by funrollloops** [comment]
Fixed in e6cf018cc9ad2ce53d561a1fcc54bdc5ed28c0db
