### ISSUE TITLE
Clicking out of the search bar

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#4]
Automatically opens whatever drink you select.  Not terrible, but a little irksome from a desktop.  Might be fine on phone.

**Comment by funrollloops** [comment]
What are you expecting to happen?

**Comment by wgmfisch** [comment]
To remove my cursor from the search bar, but not select a drink.  Honestly,
it's probably fine not to change this.  Minor complaint.

**Comment by funrollloops** [comment]
I think the common case here is to search and then select a drink immediately, so I'd rather leave this as is.

**Comment by wgmfisch** [comment]
Seems reasonable.
