### ISSUE TITLE
Use memcache to reduce datastore reads/writes

### ISSUE THREAD

**Issue by funrollloops** [nebree8/nebree8.com#47]
We did 460k reads and 10k writes on July 10.

Of those, 310k were "small" unbillable reads (key-only) and 150k were billable; The free quota is 50k/day, so we were billed $.06 for the extra 100k reads at $.60/million reads.

Most of these ops were almost certainly from checking order status. This should be easy to fix by checking/updating memcache in findOrder and mutateOrder.

Also maybe caching getConfig, but this should have been relatively few read ops.

The free quota for writes is 20k, so we were getting close there too, and those were much more expensive ($1.80/million ops).

This is also fixable with memcache: drinkProgress should write only to the cache instead of the datastore.

**Comment by audiodude** [comment]
This issue was moved to audiodude/nebree8.com#12
