### ISSUE TITLE
Add in drink

### ISSUE THREAD

**Issue by wgmfisch** [nebree8/nebree8.com#6]
"The Steve".  With image attached.  It is just a neat scotch, but with 2.5x normal volume.
![525792_10150777222903256_1514140565_n](https://cloud.githubusercontent.com/assets/13283873/10413799/2a24c010-6f6c-11e5-8249-d5228982566a.jpg)

**Comment by funrollloops** [comment]
Do you have a picture that's more square?

**Comment by wgmfisch** [comment]
Let's try this one?
![525792_10150777222903256_1514140565_n](https://cloud.githubusercontent.com/assets/13283873/10414053/3098d2e2-6f76-11e5-8022-bf8ab2e6b053.jpg)

**Comment by funrollloops** [comment]
Done in 676e261183621c5aa6049bc68e972828b28821ab
