### ISSUE TITLE
Tell users to give a chip to a lab coat to get their drink started

### ISSUE THREAD

**Issue by funrollloops** [nebree8/nebree8.com#8]
_From @funrollloops on July 21, 2015 2:51_

_Copied from original issue: funrollloops/nebree8.com#3_

**Comment by wgmfisch** [comment]
Probably only necessary for competitions?  I'm not planning to keep track at Halloween.  Thoughts?

**Comment by funrollloops** [comment]
Right, sorry, this was for DNALounge.

The frontend currently requires that we approve each drink order before it'll be sent to the robot. Should we turn that off for home use?

**Comment by wgmfisch** [comment]
No, I think that's wise.

**Comment by wgmfisch** [comment]
Wise to leave it so that it requires admin approval.

**Comment by funrollloops** [comment]
There's a "waiting for approval" status, so this is done.
